services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports: 
      - "3306:3306"
    networks:
      - custom_network

  app:
    build: &build_app
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    networks:
        - custom_network
    tty: true
    stdin_open: true

volumes:
  db-data:

networks:
  custom_network:
    driver: bridge

