# production:
#  country_detail_get_job:
#    class: CountryDetailGetJob
#    schedule: at 5am every day

development:
  country_detail_get_job:
    class: CountryDetailGetJob
    schedule: at 5am every day
